SELECT pids.PRODUCT_ID, PRODUCT_NAME, PRICE*AMOUNT_SUM as TOTAL_SALES FROM (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT_SUM FROM FOOD_ORDER WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE)=5 GROUP BY PRODUCT_ID) pids
left join FOOD_PRODUCT on FOOD_PRODUCT.PRODUCT_ID = pids.PRODUCT_ID
order by TOTAL_SALES desc, pids.PRODUCT_ID
;
 