SELECT BM.CART_ID  FROM 
(SELECT CART_ID
FROM CART_PRODUCTS 
WHERE NAME = 'Milk') BM
INNER JOIN 
(SELECT CART_ID
FROM CART_PRODUCTS 
WHERE NAME = 'Yogurt') BYT 
on BM.CART_ID = BYT.CART_ID
GROUP BY BM.CART_ID
ORDER BY CART_ID 
;