-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME FROM ANIMAL_INS 
LEFT JOIN ANIMAL_OUTS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID

WHERE 
(ANIMAL_INS.SEX_UPON_INTAKE="Intact Male" OR ANIMAL_INS.SEX_UPON_INTAKE="Intact Female")
AND
(ANIMAL_OUTS.SEX_UPON_OUTCOME="Spayed Male" OR ANIMAL_OUTS.SEX_UPON_OUTCOME="Spayed Female" OR
 ANIMAL_OUTS.SEX_UPON_OUTCOME="Neutered Male" OR ANIMAL_OUTS.SEX_UPON_OUTCOME="Neutered Female"
)