-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, HG.EMP_NO,	EMP_NAME, POSITION, EMAIL FROM HR_GRADE HG LEFT JOIN HR_EMPLOYEES HE ON HG.EMP_NO = HE.EMP_NO GROUP BY EMP_NO HAVING SUM(HG.SCORE) = (
    SELECT MAX(TOTAL)
    FROM (
        SELECT SUM(SCORE) AS TOTAL
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) T
);