SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE 
FROM (SELECT FISH_TYPE, 
      CASE 
        WHEN LENGTH IS NOT NULL THEN LENGTH
        ELSE 10
      END AS LENGTH
      FROM FISH_INFO) ST
GROUP BY FISH_TYPE
HAVING AVG(LENGTH)>=33
ORDER BY FISH_TYPE
;