SELECT IDS.car_id, 
CASE 
    WHEN RENTAL.AVAILABILITY IS NULL THEN "대여 가능"
    ELSE "대여중"
END AS AVAILABILITY 
FROM (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY GROUP BY CAR_ID) IDS
LEFT JOIN (SELECT car_id, "대여중" AS AVAILABILITY 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE<="2022-10-16" AND END_DATE>="2022-10-16") RENTAL
ON IDS.car_id = RENTAL.CAR_ID
ORDER BY CAR_ID DESC
;
 