-- 코드를 작성해주세요
SELECT SUM(COUNT) AS FISH_COUNT FROM FISH_NAME_INFO FNI 
LEFT JOIN (SELECT FISH_TYPE, COUNT(*) AS COUNT FROM FISH_INFO FI GROUP BY FISH_TYPE) C
ON C.FISH_TYPE= FNI.FISH_TYPE
WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER'
;