-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",UGB.BOARD_ID,"/", UGF.FILE_ID, FILE_NAME, FILE_EXT) FROM USED_GOODS_BOARD UGB 
LEFT JOIN USED_GOODS_FILE UGF ON UGF.BOARD_ID = UGB.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)