-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD FROM APPOINTMENT LEFT JOIN DOCTOR ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
JOIN PATIENT ON PATIENT.PT_NO = APPOINTMENT.PT_NO
WHERE APPOINTMENT.MCDP_CD="CS" AND (APNT_CNCL_YMD IS NULL OR APNT_CNCL_YMD>"2022-04-13")
AND YEAR(APNT_YMD) =2022 AND MONTH(APNT_YMD)=04 AND DAY(APNT_YMD)=13
ORDER BY APNT_YMD
;