-- 코드를 입력하세요
SELECT 
PERIOD_USED_GOODS_BOARD.TITLE, PERIOD_USED_GOODS_BOARD.BOARD_ID, PERIOD_USED_GOODS_REPLY.REPLY_ID, PERIOD_USED_GOODS_REPLY.WRITER_ID,
PERIOD_USED_GOODS_REPLY.CONTENTS
,DATE_FORMAT(PERIOD_USED_GOODS_REPLY.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM (SELECT * FROM USED_GOODS_BOARD  WHERE CREATED_DATE>="2022-10-01" AND CREATED_DATE<"2022-11-01") PERIOD_USED_GOODS_BOARD 
JOIN 
(SELECT * FROM USED_GOODS_REPLY  ) PERIOD_USED_GOODS_REPLY
ON PERIOD_USED_GOODS_BOARD.BOARD_ID = PERIOD_USED_GOODS_REPLY.BOARD_ID 
order by PERIOD_USED_GOODS_REPLY.CREATED_DATE, TITLE;