-- 코드를 입력하세요
-- 트럭 대여 금액 구하기
SELECT HISTORY_ID, ROUND(DAILY_FEE * PERIOD * (100-discount_rate)/100, 0) AS FEE FROM 
(SELECT HISTORY_ID, DAILY_FEE, PERIOD, 
CASE
    WHEN discount_rate > 0 THEN discount_rate
    ELSE 0
END AS discount_rate
FROM (SELECT HISTORY_ID, DAILY_FEE,DATEDIFF(end_date, START_DATE)+1 AS PERIOD, 
CASE
    WHEN DATEDIFF(end_date, START_DATE)+1 >=90 THEN "90일 이상"
    WHEN DATEDIFF(end_date, START_DATE)+1 >=30 THEN "30일 이상"
    WHEN DATEDIFF(end_date, START_DATE)+1 >=7 THEN "7일 이상"
    ELSE NULL
END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_CAR CAR
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE CAR.CAR_TYPE = "트럭") CT
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN 
 ON PLAN.DURATION_TYPE = CT.DURATION_TYPE AND PLAN.CAR_TYPE = '트럭') DT
 ORDER BY FEE DESC, HISTORY_ID DESC; 