SELECT TYPE_MAX.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO RI
JOIN
(SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE)
TYPE_MAX
ON TYPE_MAX.MAX_FAVORITES = RI.FAVORITES AND TYPE_MAX.FOOD_TYPE =  RI.FOOD_TYPE
ORDER BY TYPE_MAX.FOOD_TYPE DESC
;