select FISH_INFO.ID, ST.FISH_NAME, ST.LENGTH from (select FISH_NAME_INFO.FISH_TYPE, FISH_NAME_INFO.FISH_NAME, LENGTH from 
(select FISH_TYPE, max(LENGTH) as LENGTH from FISH_INFO group by FISH_TYPE)
bf left join FISH_NAME_INFO on FISH_NAME_INFO.FISH_TYPE = bf.FISH_TYPE) st
left join FISH_INFO on st.FISH_TYPE = FISH_INFO.FISH_TYPE and st.LENGTH = FISH_INFO.LENGTH
ORDER BY FISH_INFO.ID
;