SELECT ID, FISH_NAME, G.LENGTH FROM FISH_INFO FI
JOIN (
    SELECT FI.FISH_TYPE, FISH_NAME, MAX(LENGTH) AS LENGTH
    FROM FISH_NAME_INFO FNI
    LEFT JOIN FISH_INFO FI ON FI.FISH_TYPE=FNI.FISH_TYPE
    GROUP BY FISH_NAME, FISH_TYPE
) G ON FI.FISH_TYPE = G.FISH_TYPE AND FI.LENGTH = G.LENGTH
;