SELECT GT.EMP_NO, EMP_NAME, GRADE, (SAL * PLUS /100) AS BONUS FROM (SELECT EMP_NO,
CASE
    WHEN AVG(SCORE) >= 96 THEN "S"
    WHEN AVG(SCORE) >= 90 THEN "A"
    WHEN AVG(SCORE) >= 80 THEN "B"
    ELSE "C"
END GRADE,
CASE
    WHEN AVG(SCORE) >= 96 THEN 20
    WHEN AVG(SCORE) >= 90 THEN 15
    WHEN AVG(SCORE) >= 80 THEN 10
    ELSE 0
END PLUS
FROM HR_GRADE 
GROUP BY EMP_NO) GT
LEFT JOIN HR_EMPLOYEES HE ON HE.EMP_NO = GT.EMP_NO
ORDER BY GT.EMP_NO
;